server:
  port: 9006

spring:
  application:
    name: consumer-order-payment-service

eureka:
  instance:
    prefer-ip-address: true #是否使用ip地址注册
    instance-id: 192.168.170.97:${server.port} #ip地址注册
    lease-renewal-interval-in-seconds: 30 #eureka客户端向服务端发送心跳的时间间隔，单位为秒（默认30s）
    lease-expiration-duration-in-seconds: 90 #eureka服务端在收到最后一次心跳后等待时间上限，单位为秒（默认为90s），超时将剔除服务
  client:
    register-with-eureka: true #true表示向注册中心注册自己
    fetch-registry: true #需要去检索服务
    registry-fetch-interval-seconds: 30 #默认每隔30s执行一次刷新任务
    service-url:
      #设置与eureka Server交互的地址查询服务和注册服务都需要依赖这个地址
      defaultZone: http://localhost:7001/eureka,http://localhost:7002/eureka

#设置feign客户端超时时间，springcloud SRxx版本适用
ribbon:
  eureka:
    enabled: true
  ReadTimeout: 2000 #指的是建立连接所用的时间，适用于网络状况正常的情况下，两端连接所用的时间
  ConnectTimeout: 2000  #指的是建立连接后从服务器读取到可用资源所用的时间

logging:
  level:
    com.atguigu.springcloud.service.PaymentService: debug #feign日志以什么级别，监控那个接口